name: Latest blog post workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with VELOG
    runs-on: ubuntu-latest
    steps:
      with:
        feed_list: "https://v2.velog.io/rss/kangsiwoo"